name: Update README

on:
  # run automatically every 3 days
  schedule:
    - cron: "0 0 */3 * *" 
  
  # allows to manually run the job at any time
  workflow_dispatch:
  
  # run on every push on the master branch
  push:
    branches:
      - main
    
  

jobs:
  animation:
    runs-on: ubuntu-latest
    timeout-minutes: 10
    name: generate animation

    steps:
      # generates a snake game from a github user (<github_user_name>) contributions graph, output a svg animation at <svg_out_path>
      - name: generate github-contribution-grid-snake.svg
        uses: Platane/snk@v3
        with:
          github_user_name: ${{ github.repository_owner }}
          outputs: |
            dist/github-contribution-grid-snake.svg
            dist/github-contribution-grid-snake-blue.svg?color_snake=orange&color_dots=#bfd6f6,#8dbdff,#64a1f4,#4b91f1,#3c7dd9
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Set current date as env variable
        run: echo "DATE=$(date +'%Y-%m-%d %H:%M')" >> $GITHUB_ENV

      # push the content of <build_dir> to a branch
      # the content will be available at https://raw.githubusercontent.com/<github_user>/<repository>/<target_branch>/<file> , or as github page
      - name: push github-contribution-grid-snake.svg to the output branch
        uses: crazy-max/ghaction-github-pages@v3
        with:
          target_branch: dist
          build_dir: dist
          commit_message: "generate github contribution snake svg at ${{ env.DATE }}"
          keep_history: true
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  activity:
    runs-on: ubuntu-latest
    name: Update recent activity
    if: github.event_name != 'push'
    
    
    steps:
      - uses: actions/checkout@v3
      - uses: jamesgeorge007/github-activity-readme@master
        continue-on-error: true
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          COMMIT_MSG: 'update recent activity[skip ci]'
          MAX_LINES: 5
